spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 1000
  flyway:
    locations: classpath:db/migration/{vendor}
